export const ADD_PRODUCT = "ADD_PRODUCT";
export const GET_ALL_PRODUCTS = "GET_ALL_PRODUCTS";
export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const INCREMENT_CART_PRODUCT_QUANTITY = "INCREMENT_ CART_PRODUCT_QUANTITY";
export const DECREMENT_CART_PRODUCT_QUANTITY = "DECREMENT_ CART_PRODUCT_QUANTITY";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
export const REMOVE_ALL_PRODUCTS_FROM_CART = "REMOVE_ALL_PRODUCTS_FROM_CART";


export const PREV_PAGE = 'PREV_PAGE';
export const NEXT_PAGE = 'NEXT_PAGE';
export const GO_TO_PAGE = 'GO_TO_PAGE';
export const COUNT_ITEM = 'COUNT_ITEM';
